vim.keymap.set("n", "<leader>pf", "<cmd>Telescope find_files<CR>", {})
vim.keymap.set("n", "<C-p>", "<cmd>Telescope git_files<CR>", {})
vim.keymap.set("n", "<leader>ps", "<cmd>Telescope live_grep<CR>")
vim.keymap.set("n", "<leader>po", "<cmd>Telescope oldfiles<CR>")
vim.keymap.set("n", "<leader>pb", "<cmd>Telescope file_broser<CR>")
vim.keymap.set("n", "<leader>cs", "<cmd>Telescope colorscheme<CR>")
